<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
	  <UserSecretsId>eae2e70a-50ec-48ae-ae93-28dc1452be77</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Http" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
		<PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" />
		<PackageReference Include="Serilog.Sinks.OpenTelemetry" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FCG.Users.Application\FCG.Users.Application.csproj" />
		<ProjectReference Include="..\FCG.Users.Infrastructure.Auth\FCG.Users.Infrastructure.Auth.csproj" />
		<ProjectReference Include="..\FCG.Users.Infrastructure.Kafka\FCG.Users.Infrastructure.Kafka.csproj" />
		<ProjectReference Include="..\FCG.Users.Infrastructure.SqlServer\FCG.Users.Infrastructure.SqlServer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<DependentUpon>appsettings.json</DependentUpon>
		</Content>

		<Content Update="appsettings.Test.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<DependentUpon>appsettings.json</DependentUpon>
		</Content>

		<Content Update="appsettings.Docker.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<DependentUpon>appsettings.json</DependentUpon>
		</Content>
	</ItemGroup>

</Project>
