apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-users-local-config
  namespace: fcg-users
  labels:
    app.kubernetes.io/name: fcg-users
    environment: local
data:
  ASPNETCORE_ENVIRONMENT: "Docker"
  ASPNETCORE_URLS: "http://+:8080"
  Observability__ServiceName: "FCG.Users"
  Observability__EnableOtlpExporter: "false"
  Observability__OtlpEndpoint: ""
  KafkaSettings__BootstrapServers: "kafka-service.fcg-infra.svc.cluster.local:29092"
  KafkaSettings__UseSaslSsl: "false"
  KafkaSettings__UserCreatedTopic: "user-created"
  KafkaSettings__SaslUsername: ""
  KafkaSettings__SaslPassword: ""
  JwtSettings__Issuer: "FCG-User"
  JwtSettings__Audience: "FCG-Client"
  JwtSettings__AccessTokenExpirationMinutes: "60"
  JwtSettings__RefreshTokenExpirationDays: "7"
