apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fcg-users-secrets
  namespace: fcg-users
  labels:
    app.kubernetes.io/name: fcg-users
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "dd029ae6-630e-4a7d-a8f1-07183f9484e6"
    keyvaultName: "fcg-kv-fiap-2026"
    tenantId: "cf36141c-ddd7-45a7-b073-111f66d0b30c"
    objects: |
      array:
        - |
          objectName: sql-connection-users
          objectType: secret
        - |
          objectName: jwt-secret-key
          objectType: secret
        - |
          objectName: eventhub-connection
          objectType: secret
  secretObjects:
    - secretName: fcg-users-secrets
      type: Opaque
      data:
        - objectName: sql-connection-users
          key: ConnectionStrings__DefaultConnection
        - objectName: jwt-secret-key
          key: JwtSettings__SecretKey
        - objectName: eventhub-connection
          key: KafkaSettings__SaslPassword
