apiVersion: v1
kind: Service
metadata:
  name: fcg-users-service
  namespace: fcg-users
  labels:
    app.kubernetes.io/name: fcg-users
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fcg-users
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
