apiVersion: v1
kind: ServiceAccount
metadata:
  name: fcg-users-sa
  namespace: fcg-system
  annotations:
    azure.workload.identity/client-id: "${AZURE_CLIENT_ID}"
  labels:
    azure.workload.identity/use: "true"
    app.kubernetes.io/name: fcg-users
