//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCG.Users.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FCG.Users.Messages.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance cannot be negative..
        /// </summary>
        public static string BalanceCannotBeNegative {
            get {
                return ResourceManager.GetString("BalanceCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category cannot be null or empty..
        /// </summary>
        public static string CategoryCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CategoryCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect..
        /// </summary>
        public static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required to change password..
        /// </summary>
        public static string CurrentPasswordRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be null or empty..
        /// </summary>
        public static string DescriptionCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("DescriptionCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount must be between 0 and 100..
        /// </summary>
        public static string DiscountMustBeBetweenZeroAndHundred {
            get {
                return ResourceManager.GetString("DiscountMustBeBetweenZeroAndHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already in use..
        /// </summary>
        public static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be null or empty..
        /// </summary>
        public static string EmailCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("EmailCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be longer than 255 characters..
        /// </summary>
        public static string EmailCannotExceed255Characters {
            get {
                return ResourceManager.GetString("EmailCannotExceed255Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game category type is invalid..
        /// </summary>
        public static string GameCategoryIsRequired {
            get {
                return ResourceManager.GetString("GameCategoryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game category must be less than 100 characters..
        /// </summary>
        public static string GameCategoryMaxLength {
            get {
                return ResourceManager.GetString("GameCategoryMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game description is required..
        /// </summary>
        public static string GameDescriptionIsRequired {
            get {
                return ResourceManager.GetString("GameDescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game description must be less than 500 characters..
        /// </summary>
        public static string GameDescriptionMaxLength {
            get {
                return ResourceManager.GetString("GameDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum price must be greater than or equal to the minimum price..
        /// </summary>
        public static string GameMaxPriceMustBeGreaterThanMinPrice {
            get {
                return ResourceManager.GetString("GameMaxPriceMustBeGreaterThanMinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game with name {0} already exists..
        /// </summary>
        public static string GameNameAlreadyExists {
            get {
                return ResourceManager.GetString("GameNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game name is required..
        /// </summary>
        public static string GameNameIsRequired {
            get {
                return ResourceManager.GetString("GameNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game name must be less than 255 characters..
        /// </summary>
        public static string GameNameMaxLength {
            get {
                return ResourceManager.GetString("GameNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game price must be greater than zero..
        /// </summary>
        public static string GamePriceMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("GamePriceMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access level..
        /// </summary>
        public static string InvalidAccessLevel {
            get {
                return ResourceManager.GetString("InvalidAccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access token..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s role is invalid..
        /// </summary>
        public static string InvalidUserRole {
            get {
                return ResourceManager.GetString("InvalidUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string LoginEmalRequired {
            get {
                return ResourceManager.GetString("LoginEmalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        public static string LoginInvalidEmailFormat {
            get {
                return ResourceManager.GetString("LoginInvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string LoginPasswordRequired {
            get {
                return ResourceManager.GetString("LoginPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout successful. All refresh tokens have been revoked..
        /// </summary>
        public static string LogoutSuccessFull {
            get {
                return ResourceManager.GetString("LogoutSuccessFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot exceed 100 characters.
        /// </summary>
        public static string LongPassword {
            get {
                return ResourceManager.GetString("LongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null or empty..
        /// </summary>
        public static string NameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 255 characters..
        /// </summary>
        public static string NameCannotExceed255Characters {
            get {
                return ResourceManager.GetString("NameCannotExceed255Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot exceed 100 characters.
        /// </summary>
        public static string NameIsLong {
            get {
                return ResourceManager.GetString("NameIsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be at least 2 characters long..
        /// </summary>
        public static string NameMinimumLength {
            get {
                return ResourceManager.GetString("NameMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be different from current password..
        /// </summary>
        public static string NewPasswordMustBeDifferent {
            get {
                return ResourceManager.GetString("NewPasswordMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not meet the strength requirements (minimum 8 characters, number, and special character)..
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null or empty..
        /// </summary>
        public static string PasswordCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("PasswordCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        public static string PasswordMinimumLength {
            get {
                return ResourceManager.GetString("PasswordMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one letter..
        /// </summary>
        public static string PasswordMustContainLetter {
            get {
                return ResourceManager.GetString("PasswordMustContainLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one number..
        /// </summary>
        public static string PasswordMustContainNumber {
            get {
                return ResourceManager.GetString("PasswordMustContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character..
        /// </summary>
        public static string PasswordMustContainSpecialCharacter {
            get {
                return ResourceManager.GetString("PasswordMustContainSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact support..
        /// </summary>
        public static string PleaseContactSupport {
            get {
                return ResourceManager.GetString("PleaseContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price cannot be a negative value..
        /// </summary>
        public static string PriceCannotBeNegative {
            get {
                return ResourceManager.GetString("PriceCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price must be greater than zero..
        /// </summary>
        public static string PriceMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PriceMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be on or after the start date..
        /// </summary>
        public static string PromotionEndDateMustBeAfterStartDate {
            get {
                return ResourceManager.GetString("PromotionEndDateMustBeAfterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New refresh token generated..
        /// </summary>
        public static string RefreshTokenDefaultReason {
            get {
                return ResourceManager.GetString("RefreshTokenDefaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored hash value cannot be null or empty..
        /// </summary>
        public static string StoredHashCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StoredHashCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred!.
        /// </summary>
        public static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already an Admin..
        /// </summary>
        public static string UserAlreadyAdmin {
            get {
                return ResourceManager.GetString("UserAlreadyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already a User..
        /// </summary>
        public static string UserAlreadyUser {
            get {
                return ResourceManager.GetString("UserAlreadyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id cannot be null or empty..
        /// </summary>
        public static string UserIdRequired {
            get {
                return ResourceManager.GetString("UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id: {0} was not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID {0} not found for update..
        /// </summary>
        public static string UserNotFoundForUpdate {
            get {
                return ResourceManager.GetString("UserNotFoundForUpdate", resourceCulture);
            }
        }
    }
}
